// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolutionReact.Server.Models;

#nullable disable

namespace SolutionReact.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolutionReact.Server.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdditionalRequirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaximumAge")
                        .HasColumnType("int");

                    b.Property<int?>("MinimumAge")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityName = "Sightseeing",
                            AddedBy = "Admin",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(2997),
                            AdditionalRequirements = "Swimming Certificate",
                            Description = "Visit famous landmarks",
                            DurationInMinutes = 120,
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            ActivityName = "Hiking",
                            AddedBy = "Admin",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(3000),
                            AdditionalRequirements = "None",
                            Description = "Mountain trek",
                            DurationInMinutes = 180,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SolutionReact.Server.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookingStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomTourScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NoPax")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingStatusId");

                    b.HasIndex("CustomTourScheduleId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedBy = "Admin",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(3095),
                            BookingDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(3092),
                            BookingStatusId = 2,
                            CustomTourScheduleId = 1,
                            CustomerId = 1,
                            IsActive = true,
                            NoPax = 2,
                            TotalPrice = 3000m
                        },
                        new
                        {
                            Id = 2,
                            AddedBy = "Admin",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(3099),
                            BookingDate = new DateTime(2025, 11, 22, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(3098),
                            BookingStatusId = 1,
                            CustomTourScheduleId = 2,
                            CustomerId = 2,
                            IsActive = true,
                            NoPax = 1,
                            TotalPrice = 1200m
                        });
                });

            modelBuilder.Entity("SolutionReact.Server.Models.BookingParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("CustomerId");

                    b.ToTable("BookingsParticipant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedBy = "Admin",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(3410),
                            BookingId = 1,
                            CustomerId = 1,
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            AddedBy = "Admin",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(3412),
                            BookingId = 1,
                            CustomerId = 2,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SolutionReact.Server.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhoneNumberExtra")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedBy = "Admin",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(3064),
                            City = "Paris",
                            Country = "France",
                            DateOfBirth = new DateTime(1990, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "alice.johnson@example.com",
                            FirstName = "Alice",
                            HomeAddress = "789 Elm St",
                            IsActive = true,
                            LastName = "Johnson",
                            PhoneNumber = "555-1234",
                            PostCode = "12345"
                        },
                        new
                        {
                            Id = 2,
                            AddedBy = "Admin",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(3069),
                            City = "Florence",
                            Country = "Italy",
                            DateOfBirth = new DateTime(1988, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "bob.williams@example.com",
                            FirstName = "Bob",
                            HomeAddress = "456 Oak Ave",
                            IsActive = true,
                            LastName = "Williams",
                            PhoneNumber = "555-5678",
                            PostCode = "67890"
                        });
                });

            modelBuilder.Entity("SolutionReact.Server.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Destination");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedBy = "Admin",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(2930),
                            City = "Paris",
                            Country = "France",
                            IsActive = true,
                            Region = "Ile-de-France"
                        },
                        new
                        {
                            Id = 2,
                            AddedBy = "Admin",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(2933),
                            City = "Florence",
                            Country = "Italy",
                            IsActive = true,
                            Region = "Tuscany"
                        });
                });

            modelBuilder.Entity("SolutionReact.Server.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AmountInvoice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("AmountPaid")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateInvoice")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePayment")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedBy = "Admin",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(3353),
                            AmountInvoice = 1500m,
                            AmountPaid = 1500m,
                            BookingId = 1,
                            DateInvoice = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(3345),
                            DatePayment = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(3348),
                            IsActive = true,
                            PaymentMethodId = 1,
                            TransactionReference = "TX12345"
                        },
                        new
                        {
                            Id = 2,
                            AddedBy = "Admin",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(3358),
                            AmountInvoice = 1200m,
                            BookingId = 2,
                            DateInvoice = new DateTime(2025, 11, 22, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(3355),
                            IsActive = true,
                            PaymentMethodId = 2,
                            TransactionReference = "TX54321"
                        });
                });

            modelBuilder.Entity("SolutionReact.Server.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedBy = "System",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(2569),
                            Description = "Payment via major credit cards",
                            IsActive = true,
                            Name = "Credit Card"
                        },
                        new
                        {
                            Id = 2,
                            AddedBy = "System",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(2628),
                            Description = "Payment via PayPal account",
                            IsActive = true,
                            Name = "PayPal"
                        },
                        new
                        {
                            Id = 3,
                            AddedBy = "System",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(2630),
                            Description = "Direct bank transfer",
                            IsActive = true,
                            Name = "Bank Transfer"
                        },
                        new
                        {
                            Id = 4,
                            AddedBy = "System",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(2632),
                            Description = "Cash payment at counter",
                            IsActive = true,
                            Name = "Cash"
                        });
                });

            modelBuilder.Entity("SolutionReact.Server.Models.StatusOfEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("StatusOfEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedBy = "System",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(2893),
                            IsActive = true,
                            StatusDescription = "Pending confirmation",
                            StatusName = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            AddedBy = "System",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(2897),
                            IsActive = true,
                            StatusDescription = "Confirmed",
                            StatusName = "Confirmed"
                        },
                        new
                        {
                            Id = 3,
                            AddedBy = "System",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(2899),
                            IsActive = true,
                            StatusDescription = "Cancelled",
                            StatusName = "Cancelled"
                        },
                        new
                        {
                            Id = 4,
                            AddedBy = "System",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(2902),
                            IsActive = true,
                            StatusDescription = "Completed",
                            StatusName = "Completed"
                        });
                });

            modelBuilder.Entity("SolutionReact.Server.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LengthInDays")
                        .HasColumnType("int");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TourCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("Tours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedBy = "Admin",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(2966),
                            DestinationId = 1,
                            IsActive = true,
                            LengthInDays = 7,
                            MaxParticipants = 20,
                            Price = 1500m,
                            TourCode = "ADV-001"
                        },
                        new
                        {
                            Id = 2,
                            AddedBy = "Admin",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(2970),
                            DestinationId = 2,
                            IsActive = true,
                            LengthInDays = 5,
                            MaxParticipants = 15,
                            Price = 1200m,
                            TourCode = "CUL-001"
                        });
                });

            modelBuilder.Entity("SolutionReact.Server.Models.TourActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DayScheduled")
                        .HasColumnType("int");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("TourId");

                    b.ToTable("TourActivities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityId = 1,
                            AddedBy = "Admin",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(3381),
                            IsActive = true,
                            TourId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActivityId = 2,
                            AddedBy = "Admin",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(3384),
                            IsActive = true,
                            TourId = 1
                        });
                });

            modelBuilder.Entity("SolutionReact.Server.Models.TourSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AvailablePax")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TourStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TourStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.HasIndex("TourStatusId");

                    b.ToTable("ToursSchedule");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedBy = "Admin",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(3026),
                            AvailablePax = 0,
                            IsActive = true,
                            TourId = 1,
                            TourStartDate = new DateTime(2025, 12, 3, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(3023),
                            TourStatusId = 2
                        },
                        new
                        {
                            Id = 2,
                            AddedBy = "Admin",
                            AddedDate = new DateTime(2025, 11, 23, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(3031),
                            AvailablePax = 0,
                            IsActive = true,
                            TourId = 2,
                            TourStartDate = new DateTime(2025, 12, 13, 22, 0, 34, 484, DateTimeKind.Local).AddTicks(3029),
                            TourStatusId = 1
                        });
                });

            modelBuilder.Entity("SolutionReact.Server.Models.Booking", b =>
                {
                    b.HasOne("SolutionReact.Server.Models.StatusOfEntity", "StatusOfEntity")
                        .WithMany("Bookings")
                        .HasForeignKey("BookingStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionReact.Server.Models.TourSchedule", "TourSchedule")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomTourScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionReact.Server.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("StatusOfEntity");

                    b.Navigation("TourSchedule");
                });

            modelBuilder.Entity("SolutionReact.Server.Models.BookingParticipant", b =>
                {
                    b.HasOne("SolutionReact.Server.Models.Booking", "Booking")
                        .WithMany("BookingParticipants")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolutionReact.Server.Models.Customer", "Customer")
                        .WithMany("BookingParticipants")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SolutionReact.Server.Models.Payment", b =>
                {
                    b.HasOne("SolutionReact.Server.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolutionReact.Server.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("SolutionReact.Server.Models.Tour", b =>
                {
                    b.HasOne("SolutionReact.Server.Models.Destination", "Destination")
                        .WithMany("Tours")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("SolutionReact.Server.Models.TourActivity", b =>
                {
                    b.HasOne("SolutionReact.Server.Models.Activity", "Activity")
                        .WithMany("TourActivities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionReact.Server.Models.Tour", "Tour")
                        .WithMany("TourActivities")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("SolutionReact.Server.Models.TourSchedule", b =>
                {
                    b.HasOne("SolutionReact.Server.Models.Tour", "Tour")
                        .WithMany("TourSchedules")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionReact.Server.Models.StatusOfEntity", "StatusOfEntity")
                        .WithMany("TourSchedules")
                        .HasForeignKey("TourStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StatusOfEntity");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("SolutionReact.Server.Models.Activity", b =>
                {
                    b.Navigation("TourActivities");
                });

            modelBuilder.Entity("SolutionReact.Server.Models.Booking", b =>
                {
                    b.Navigation("BookingParticipants");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SolutionReact.Server.Models.Customer", b =>
                {
                    b.Navigation("BookingParticipants");

                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("SolutionReact.Server.Models.Destination", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("SolutionReact.Server.Models.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SolutionReact.Server.Models.StatusOfEntity", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("TourSchedules");
                });

            modelBuilder.Entity("SolutionReact.Server.Models.Tour", b =>
                {
                    b.Navigation("TourActivities");

                    b.Navigation("TourSchedules");
                });

            modelBuilder.Entity("SolutionReact.Server.Models.TourSchedule", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
